/*
 *    Filename:	CustSlider.h 
 *    Created :	Wed May 27 15:16:04 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *    LastEditDate was "Wed May 27 22:26:50 1992"
 *
 *    $Id: CustSlider.h,v 1.1 2002-03-21 16:49:51 rao Exp $
 *
 *    $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  13:49:29  vince
 * Initial Version
 *
 */

/* Generated by Interface Builder */

/* THis object provides a slider that will send a message to target2 when the
 * User does a mouseUp.  Basically it provides continuous and non-continuous
 * Slider Behaviour all within one slider.
 */

#import <appkit/Slider.h>

@interface CustSlider:Slider
{
}

+ initialize;
- target2;                    // Returns the target of the mouseUp event
- setTarget2:anObject;        // Sets the target object when a mouseUp event occurs
- (SEL)action2;               // Returns the selector that will get called on mouseUp
- setAction2:(SEL)aSelector;  // Sets the selector that will get called on mouseUp

@end
