/*
 *    Filename:	CustSlider.m 
 *    Created :	Wed May 27 15:16:08 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *    LastEditDate was "Wed May 27 15:26:44 1992"
 *
 *    $Id: CustSlider.m,v 1.1 2002-03-21 16:49:51 rao Exp $
 *
 *    $Log: not supported by cvs2svn $
# Revision 2.1  1992/06/10  13:49:29  vince
# Initial Version
#
 */


/* Generated by Interface Builder */

#import "CustSlider.h"
#import "CustSliderCell.h"

@implementation CustSlider
+ initialize
{
    [super initialize];
    if (self == [CustSlider class]){
	[self setCellClass:[CustSliderCell class]];
    }
    return self;
}

- target2
{
    return [cell target2];
}

- setTarget2:anObject
{
    return [cell setTarget2:anObject];
}

- (SEL)action2
{
    return [cell action2];
}

- setAction2:(SEL)aSelector
{
    return [cell setAction2:aSelector];
}

@end
