/*
 *    Filename:	CustSliderCell.h 
 *    Created :	Wed May 27 15:16:14 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *    LastEditDate was "Wed May 27 22:29:24 1992"
 *
 *    $Id: CustSliderCell.h,v 1.1 2002-03-21 16:49:51 rao Exp $
 *
 *    $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  13:50:49  vince
 * *** empty log message ***
 *
 */

/* The actual functionality of the CustSlider is provided by the CustSliderCell.
 * all that I did was provide the trackMouse:inRect:ofView: method with some extra functionality
 * What happens is this:
 * after the super trackMouse:inRect:ofView: returns I know that a mouseUp event has occured
 * therefore i simply send a action (using Control's sendAction:to: method) to target2 calling
 * the selector action2
 */

/* Generated by Interface Builder */

#import <appkit/SliderCell.h>

@interface CustSliderCell:SliderCell
{
    id  target2;
    SEL action2;

}

- (BOOL)trackMouse:(NXEvent *)theEventTracks inRect:(const NXRect *)cellFrame ofView:controlView;
- setTarget2:anObject;
- setAction2:(SEL)aSelector;
- target2;
- (SEL)action2;

@end
