/*
 *    Filename:	Help.h 
 *    Created :	Wed Jan  8 23:34:39 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *
 * LastEditDate "Tue May 26 22:57:20 1992"
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  13:54:40  vince
 * More Entries have been added to the help window
 * and each time the window is displayed the
 * What is PrEditor? option is displayed.
 *
 * Revision 2.0  1992/04/08  03:43:23  vince
 * Initial-Release
 *
 *
 */


/* Generated by Interface Builder */

#import <objc/Object.h>
#import <dpsclient/event.h> // For NXSize
#import <appkit/graphics.h> // For NXRect
#import <objc/zone.h>

@interface Help:Object
{
    NXZone *helpZone;
    id	helpBrowser;
    id	helpScrollView;
    id  helpWindow;
    NXRect WindowRect;
}

+ initialize;
- init;
- free;
- help:sender;
- browserHit:sender;
- showHelpFile:(const char*)filename;
- print:sender;

/* Browser Delegation Methods */
- (int)browser:sender fillMatrix:matrix inColumn:(int)column;

/* Window Delegation Methods */
- windowWillResize:sender toSize:(NXSize *)frameSize;
- windowDidUpdate:sender;

@end
