/*
 *    Filename:	InfoMgr.h 
 *    Created :	Sun Oct 20 20:38:52 1991 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *
 * LastEditDate "Wed May 13 18:50:13 1992"
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  13:57:44  vince
 * Make suggestions option has been added. This will start
 * up the Mail.app to allow the user to send in bug reports
 *
 * Revision 2.0  1992/04/08  03:43:23  vince
 * Initial-Release
 *
 *
 */


/* Generated by Interface Builder */

#import <objc/Object.h>

#define SUGGESTION_RECIEVER  "ttsinfo@trillium.ab.ca"
#define CARBON_COPY_RECIEVER "manzara@trillium.ab.ca"

@interface InfoMgr:Object
{
    id	infoPanel;
    id  appIconButton;
    id  preditorVersion;
    id  serverVersion;
    id  compileDate;
    id  compileTime;
}

- info:sender;
- makeSuggestion:sender;

/* Info Panel Delegation Methods */
- windowWillClose:sender;
- windowDidBecomeKey:sender;

@end
