/*
 *    Filename:	KeyboardController.h 
 *    Created :	Sat Jan 18 19:32:11 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *
 * LastEditDate "Sat Jun  6 13:06:09 1992"
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  14:01:13  vince
 * Method to toggle the Keyboard has been added. (Ie if the
 * shift keys are down, toggleShift: will switch the shift keys
 * so they are up, and visa versa)
 *
 * Revision 2.0  1992/04/08  03:43:23  vince
 * Initial-Release
 *
 *
 */


/* Generated by Interface Builder */

#import <objc/Object.h>

@interface KeyboardController:Object
{
    id	numberKeys;         /* esc to =  */
    id	qToP;               /* q   to \  */
    id	aToL;               /* a   to '  */
    id	zToM;               /* z   to /  */
    id	deleteKey;
    id	rightShiftKey;
    id	leftShiftKey;
    id	returnKey;
    id	space;
    BOOL shiftDown;
    BOOL sendAction;
    BOOL enabled;
    id  window;
    id	target;
}

- init;
- pressKey: (const char)key;
- shiftDown:sender;
- shiftUp:sender;
- leftShift:sender;
- rightShift:sender;
- toggleShift:sender;
- shiftKeys:sender;
- setFont: fontObj;

- disableKeyboard;
- enableKeyboard;
- recieveAction:sender;
@end

