/*
 *    Filename:	KeyboardText.h 
 *    Created :	Thu Feb  6 21:44:14 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *
 * LastEditDate "Sat Jun  6 14:03:29 1992"
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  14:02:11  vince
 * KeyboardTextCell is no longer in use.
 * a Custom TextObject (MyText) with new delegation
 * methods is being used to handle the filter
 * functions.
 * The bug involving the Charfilter function not being
 * properly installed has been fixed, by reinstalling
 * it each time there is a keyDown or a mouseDown event.
 * This Object will now also shift the keyboard if the
 * shift key is pressed, as long as NX_SHIFTMASK has been
 * added to the windows event mask
 *
 * Revision 2.0  1992/04/08  03:43:23  vince
 * Initial-Release
 *
 *
 */


/* Generated by Interface Builder */
#import <objc/Object.h>
#import "MyText.h"

@interface KeyboardText:Object
{
    NXCharFilterFunc oldCharFilter; /* hold original filter func */
    id textField;
    id keyboard;
}

/* Force a key to be inserted into the KeyBoard Text Field */
- insertKey:(const char)character;
- delete;
/* Text Object Delegation methods */
- textDidEnd:textObject endChar:(unsigned short)whyEnd;
- textDidGetKey:textObject charCode:(unsigned short int) charCode;
- textFlagsDidChange:textObject flags:(int) theflags keyCode:(unsigned int)keyCode;
- (BOOL)textWillChange:textObject;
- textDidMouseDown:textObject;
@end
