/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import "PrEditorApp.h"

void main(int argc, char *argv[]) {

    [PrEditorApp new];
    if ([NXApp loadNibSection:"PrEditor.nib" owner:NXApp withNames:NO])
	    [NXApp run];
	    
    [NXApp free];
    exit(0);
}
