/*
 *    Filename:	PrEditorApp.h 
 *    Created :	Tue Jan 14 21:47:09 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *
 * LastEditDate "Tue Jun  2 14:30:55 1992"
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  14:22:17  vince
 * Methods to return:
 * - wordList -> Return a pointer to the wordList
 * (aka PrDictViewer object)
 *
 * - mainDocument -> Return a pointer to PrEditorDocument Object
 * currently being edited (mainWindow)
 *
 * Revision 2.0  1992/04/08  03:43:23  vince
 * Initial-Release
 *
 *
 */


/* Generated by Interface Builder */

#import <appkit/Application.h>
#import <objc/zone.h>

@interface PrEditorApp:Application
{
    id inspectorObject; /* InspectorMgr Object Instance */
    id wordList;        /* PrDictViewer Object Instance */
    id zoneList;        /* List Object containing a list of zones currently
			 * in use by the application
			 * this is to allow reuse of the zones
			 */
    id prefMgrObject;
}

+ new;
- free;
- appDidInit:sender;

/* Create a new Document */
- newDocument:sender;

/* Open an existing Document */
- open:sender;
- (int)openFile:(const char *)fullPath ok:(int *)flag;
- (BOOL)appAcceptsAnotherFile:sender;
- saveAll:sender;
- appWillTerminate:sender;

/* Return the title of the NeXT untitiled Document
 * This ensures that all titles will be unique
 */
- (char *) untitled;

/* Return a pointer to the wordList (aka Current Dictionary Contents Object) */
- wordList;
/* Return a pointer to the currently being editied PrEditorDocument Object */
- mainDocument;

/* Automatic update methods */
- (BOOL)menuItemUpdate:menuCell;
- (BOOL)validateCommand:menuCell;

/* Return a pointer to the InspectorMgr Object */
- inspectorPanel;

/* Reusing Zones */
- (NXZone *)newZone;
- (void)reuseZone:(NXZone *)aZone;

@end
