/*
 *    Filename:	PrefMgr.h 
 *    Created :	Sun Feb 23 15:49:09 1992 
 *    Author  :	Vince DeMarco
 *		<vince@whatnxt.cuc.ab.ca>
 *
 * LastEditDate "Tue Jun  2 14:23:17 1992"
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.1  1992/06/10  14:33:05  vince
 * This object now sets all of the default values
 * for the TextToSpeech Kit. After a value has been changed
 * a test phrase is spoken to allow the user to see if the
 * change that he/she has made is okay.
 *
 * Revision 2.0  1992/04/08  03:43:23  vince
 * Initial-Release
 *
 *
 */


/* Generated by Interface Builder */

#import <objc/Object.h>

#define TEST_SENTENCE "This is a test of the Text to Speech Settings."

@interface PrefMgr:Object
{
    id	window;
    id  speechObject;

    id  currentView;
    id  generalView;
    id  speechQualityView;
    id  dictionarySettingsView;

    id  intonation;
    id  volume;
    id  speed;
    id  channels;
    id  balance;
    id  pitchOffset;
    id  vtlOffset;
    id  voiceType;
    id  breathiness;

    id  volumeField;
    id  speedField;
    id  pitchOffsetField;
    id  vtlOffsetField;
    id  balanceField;
    id  breathinessField;
    id  userDictionaryField;

    id  testSentenceField;

    id  userDictPathRevertButton;
    id  userDictPathAcceptButton;

}

+ initialize;
- free;

- preferences:sender;

- revertAll:sender;

- switchViews:sender;

- setTestSentence:sender;
- setINtonation:sender;
- setUSerDictPath:sender;
- revertUserDictPath:sender;
- acceptUserDictPath:sender;

- setVOlume:sender;
- setCHannels:sender;
- setBAlance:sender;
- setSPeed:sender;
- setPitchOFFset:sender;
- setVtlOFFset:sender;
- setVOiceType:sender;
- setBReathiness:sender;

- sayTestSentence:sender;

/* Window Delegations Methods */
- windowWillClose:sender;

@end
