
include $(GNUSTEP_MAKEFILES)/common.make

# The application to be compiled
APP_NAME = Synthesizer

# Main model file
Synthesizer_MAIN_MODEL_FILE = MainMenu.gorm

# The Objective-C source files to be compiled
Synthesizer_OBJC_FILES = \
AboutView.m \
Analysis.m \
AnalysisWindow.m \
ChartView.m \
Controller.m \
Crossmix.m \
FricativeArrow.m \
GlottalSource.m \
GPParamView.m \
Harmonics.m \
main.m \
PitchScale.m \
Spectrograph.m \
Spectrum.m \
TubeSection.m \
VelarNasalConnector.m \
VelumSlider.m \
Waveform.m

Synthesizer_C_FILES = \
conversion.c \
fft.c \
tube.c

# The Resource files to be copied into the app's resources directory
Synthesizer_RESOURCE_FILES = \
Images/00-gray.tif \
Images/01-gray.tif \
Images/02-gray.tif \
Images/03-gray.tif \
Images/04-gray.tif \
Images/05-gray.tif \
Images/06-gray.tif \
Images/07-gray.tif \
Images/08-gray.tif \
Images/09-gray.tif \
Images/100-gray.tif \
Images/10-gray.tif \
Images/11-gray.tif \
Images/12-gray.tif \
Images/13-gray.tif \
Images/14-gray.tif \
Images/15-gray.tif \
Images/16-gray.tif \
Images/17-gray.tif \
Images/18-gray.tif \
Images/19-gray.tif \
Images/20-gray.tif \
Images/21-gray.tif \
Images/22-gray.tif \
Images/23-gray.tif \
Images/24-gray.tif \
Images/25-gray.tif \
Images/26-gray.tif \
Images/27-gray.tif \
Images/28-gray.tif \
Images/29-gray.tif \
Images/30-gray.tif \
Images/31-gray.tif \
Images/32-gray.tif \
Images/33-gray.tif \
Images/34-gray.tif \
Images/35-gray.tif \
Images/36-gray.tif \
Images/37-gray.tif \
Images/38-gray.tif \
Images/39-gray.tif \
Images/40-gray.tif \
Images/41-gray.tif \
Images/42-gray.tif \
Images/43-gray.tif \
Images/44-gray.tif \
Images/45-gray.tif \
Images/46-gray.tif \
Images/47-gray.tif \
Images/48-gray.tif \
Images/49-gray.tif \
Images/50-gray.tif \
Images/51-gray.tif \
Images/52-gray.tif \
Images/53-gray.tif \
Images/54-gray.tif \
Images/55-gray.tif \
Images/56-gray.tif \
Images/57-gray.tif \
Images/58-gray.tif \
Images/59-gray.tif \
Images/60-gray.tif \
Images/61-gray.tif \
Images/62-gray.tif \
Images/63-gray.tif \
Images/64-gray.tif \
Images/65-gray.tif \
Images/66-gray.tif \
Images/67-gray.tif \
Images/68-gray.tif \
Images/69-gray.tif \
Images/70-gray.tif \
Images/71-gray.tif \
Images/72-gray.tif \
Images/73-gray.tif \
Images/74-gray.tif \
Images/75-gray.tif \
Images/76-gray.tif \
Images/77-gray.tif \
Images/78-gray.tif \
Images/79-gray.tif \
Images/80-gray.tif \
Images/81-gray.tif \
Images/82-gray.tif \
Images/83-gray.tif \
Images/84-gray.tif \
Images/85-gray.tif \
Images/86-gray.tif \
Images/87-gray.tif \
Images/88-gray.tif \
Images/89-gray.tif \
Images/90-gray.tif \
Images/91-gray.tif \
Images/92-gray.tif \
Images/93-gray.tif \
Images/94-gray.tif \
Images/95-gray.tif \
Images/96-gray.tif \
Images/97-gray.tif \
Images/98-gray.tif \
Images/99-gray.tif \
Synthesizer.icns \
synth.icns \
AboutSynthesizer.pdf \
Info.plist

Synthesizer_LANGUAGES = English

Synthesizer_LOCALIZED_RESOURCE_FILES = \
MainMenu.gorm

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
