
/* Generated by Interface Builder */

#import <objc/Object.h>

@interface myController:Object
{
    id	hostid;
    id	password;
    id	decryptButton;
}

- appDidInit:sender;
- decrypt:sender;
- (const char *) appDirectory;

@end
