
/* Generated by Interface Builder */

#import <stdio.h>
#import <string.h>
#import <sys/file.h>
#import "../SpeechMessages.h"
#import "../MessageStructs.h"

extern void gethostname();
extern void mach_error();

static port_t outPort, localPort;

extern void send_simple_message();
extern void send_string_message();
extern void send_float_message();
extern void send_int_message();
extern void receive_simple_message();
extern void receive_string_message();
extern void receive_float_message();
extern void receive_int_message();

int init_local_port()
{
kern_return_t error;

	/* Allocate a new port */
        if ((error = port_allocate(task_self(),&localPort))!=KERN_SUCCESS)
		return(1);

	return(0);			/* Return Success */
}

int connect_speech_port()
{
kern_return_t error;
char hostname[64];

	/* Get hostname for use in netname_look_up */
	gethostname(hostname, 64);

	/* Get Speech Port */
	error = netname_look_up(name_server_port, hostname, SPEECH_PORT_NAME, &outPort); /* Find port */

	if (error!=KERN_SUCCESS)
		return(1);

	return(0);			/* Return Success */
}

int initiate_connection(SpeechIdentifier)
int *SpeechIdentifier;
{
struct simple_msg message;
struct int_msg reply_message;

	/* Tell server we wish to use its services */
	send_simple_message(outPort, localPort, NEW_SPEAKER, 0);

	/* Wait for reply.  If -1 returned, we cannot connect */
	receive_int_message(localPort, &reply_message);

	*SpeechIdentifier = reply_message.data;	/* Return ident in int message  */
	if (*SpeechIdentifier == (-1)) return(1);
	else return(0);
}

main(argc, argv)
int argc;
char *argv[];
{
int SpeechIdentifier;
struct string_msg message;

	if (argc!=2) exit(0);
	if (init_local_port() !=0)
	{
		fprintf(stderr,"Cannot intialize local reply port\n");
		exit(1);
	}
	if (connect_speech_port()!=0)
	{
		fprintf(stderr,"Cannot connect to speech server\n");
		exit(1);
	}
	if (initiate_connection(&SpeechIdentifier) == 0)
	{
		send_string_message(outPort, localPort, SPEAKTEXT, 0, argv[1]);
		receive_int_message(localPort, &message);
		send_simple_message(outPort, localPort, CLOSE_SPEAKER, SpeechIdentifier);
	}
}