#define NXDEFAULT_OWNER			"WhosOnFirst"
#define NXDEFAULT_NUMBER		7

#define NXDEFAULT_SPEAK_LOGIN		"speakLogin"
#define NXDEFAULT_SPEAK_LOGOUT		"speakLogout"
#define NXDEFAULT_WHEN_TO_SPEAK		"whenToSpeak"
#define NXDEFAULT_LOGIN_MESSAGE		"loginMessage"
#define NXDEFAULT_LOGOUT_MESSAGE	"logoutMessage"
#define NXDEFAULT_DOUBLE_CLICK_ACTION	"doubleClickAction"
#define NXDEFAULT_CONFIRM_DOUBLE_CLICK	"confirmDoubleClick"

#define LOGIN_DEF			"YES"
#define LOGOUT_DEF			"YES"
#define WHEN_TO_SPEAK_DEF		"1"
#define LOGIN_MESSAGE_DEF		"%u logged in on %t."
#define LOGOUT_MESSAGE_DEF		"%u logged out."
#define DOUBLE_CLICK_ACTION_DEF		"0"
#define CONFIRM_DOUBLE_CLICK_DEF	"NO"


NXDefaultsVector WhosOnFirstDefaults = {
	{NXDEFAULT_SPEAK_LOGIN,		LOGIN_DEF},
	{NXDEFAULT_SPEAK_LOGOUT,	LOGOUT_DEF},
	{NXDEFAULT_WHEN_TO_SPEAK,	WHEN_TO_SPEAK_DEF},
	{NXDEFAULT_LOGIN_MESSAGE,	LOGIN_MESSAGE_DEF},
	{NXDEFAULT_LOGOUT_MESSAGE,	LOGOUT_MESSAGE_DEF},
	{NXDEFAULT_DOUBLE_CLICK_ACTION,	DOUBLE_CLICK_ACTION_DEF},
	{NXDEFAULT_CONFIRM_DOUBLE_CLICK,CONFIRM_DOUBLE_CLICK_DEF},
	{NULL,				 NULL}
};
