
/* Generated by Interface Builder */

#import <objc/Object.h>
#import <appkit/View.h>

/*  DEFINITIONS  */
#define SYMBOL_LENGTH_MAX       12
#define ROW_NUMBER_MAX          5

#define FONTNAME                "Courier"
#define FONTSIZE                12.0

#define CATEGORY_SYMBOL_DEF	""  /*  put this in a global .h file  */

#define CATEGORY_SYMBOL         0
#define CATEGORY_ORDER		1

/*  SUB WINDOW OFFSETS  */
#define CATEGORY_X_OFFSET       (-15)
#define CATEGORY_Y_OFFSET       (-79)


/*  DATA STRUCTURES  */
struct _categoryStruct {
  char symbol[SYMBOL_LENGTH_MAX+1];
  struct _categoryStruct *next;
};

typedef struct _categoryStruct categoryStruct;
typedef categoryStruct *categoryStructPtr;

@interface Categories:Object
{
    id template;
    id phoneDescriptionObj;
    id ruleObj;

    id	categoriesWindow;
    id	categoryList;
    id	categoryTotal;

    id	addCategoryPanel;
    id	addCategoryField;

    id	modCategoryPanel;
    id	modCategoryField;

    id  categoryModButton;

    NXRect r;

    int number_of_categories;
    categoryStructPtr categoryHead;
    int categoryCurrentRow;

    id  fontObj;
}
- appDidInit:sender;

- addCategory:sender;
- modCategory:sender;

- addCategoryCancel:sender;
- addCategoryAdd:sender;

- modCategoryCancel:sender;
- modCategoryDelete:sender;
- modCategoryOK:sender;

- (int)usedAsCategorySymbol:(char *)string;
- (char *)symbolAtRow:(int)row;
- (int)numberOfCategories;

- saveToFile:(FILE *)fp1;
- readFromFile:(FILE *)fp1;
@end
