/* Generated by Interface Builder */

#import <objc/Object.h>
#import <appkit/View.h>
#import <stdio.h>

/*  DEFINITIONS  */
#define SYMBOL_LENGTH_MAX       12
#define ROW_NUMBER_MAX          5

#define FONTNAME                "Courier"
#define FONTSIZE                12.0

/*  SUB WINDOW OFFSETS  */
#define MODTARGET_X_OFFSET       (232)
#define MODTARGET_Y_OFFSET       (17)
#define CATEGORIZE_X_OFFSET      (504)
#define CATEGORIZE_Y_OFFSET      (17)

#define DURATION_DEF             100
#define T_DURATION_FIXED_DEF     20
#define T_DURATION_FIXED         0
#define T_DURATION_PROP          1


#define TARGET_MATRIX_PARAM      0
#define TARGET_MATRIX_MIN        1
#define TARGET_MATRIX_MAX        2
#define TARGET_MATRIX_DEF        3

/*  DATA STRUCTURES  */
struct _target {
  int is_default;
  float value;
  struct _target *next;
};

typedef struct _target target;
typedef target *targetPtr;

struct _category {
  char symbol[SYMBOL_LENGTH_MAX+1];
  struct _category *next;
};

typedef struct _category category;
typedef category *categoryPtr;

struct _phoneDescription {
  char symbol[SYMBOL_LENGTH_MAX+1];
  int duration;
  struct {
      int type;
      int fixed;
      float prop;
  } transition_duration;
  struct _phoneDescription *next;
  targetPtr targetHead;
  categoryPtr categoryHead;
  int number_of_categories;
};

typedef struct _phoneDescription phoneDescription;
typedef phoneDescription *phoneDescriptionPtr;


@interface PhoneDescription:Object
{
    id	categories;
    id	template;
    id  ruleObj;

    id	phoneDescriptionWindow;
    id	modTargetPanel;
    id	addCategorizePanel;

    id	displayCurrentPhone;
    id	phoneList;

    id	displayPhoneDuration;
    id  transitionDurField;
    id  transitionDurLabel;
    id  transitionDurSwitch;

    id	targetList;

    id	categoryList;

    id	modTargetForm;
    id  modTargetSwitch;
    id	modTargetMatrix;

    id	addCategorizeList;
    id	addCategorizeForm;

    id  targetModButton;
    id  categoryDeleteButton;
    id  categoryAddButton;
    id  categorizeAddButton;

    id  fontObj;

    NXRect r;

    int phoneCurrentRow;
    int targetCurrentRow;
    int categoryCurrentRow;
    int addCategorizeCurrentRow;

    int number_of_phones;
    int number_of_targets;

    phoneDescriptionPtr phoneDescriptionHead;
    phoneDescriptionPtr currentDescriptionPtr;

    targetPtr currentTargetPtr;
}

- appDidInit:sender;

- setTitleBar:(char *)currentPath;

- modifyTarget:sender;

- addCategory:sender;
- deleteCategory:sender;

- modDurationOK:sender;
- modTransitionDurOK:sender;
- fixedTransitionDur:sender;
- propTransitionDur:sender;

- modTargetCancel:sender;
- modTargetDefault:sender;
- modTargetOK:sender;

- addCategorizeCancel:sender;
- addCategorizeAdd:sender;

- addPhone:(char *)string order:(int)order;
- deletePhone:(int)row;
- modPhone:(char *)string row:(int)row order:(int)order;

- propagateModCategory:(char *)old_symbol :(char *)new_symbol;
- propagateDeleteCategory:(char *)old_symbol;

- addDefaultTargets:(phoneDescriptionPtr)phone_ptr;
- propagateDeleteTarget:(int)currentRow;
- propagateAddTarget:(int)order;
- propagateModParam:(int)old_order:(int)new_order;

- propagateSetSample:(int)new_size;

- (int)matchPhone:(char *)phone ToCategory:(char *)category;

- (float)getTarget:(char *)phone:(char *)parameter;
- (int)getPhoneLength:(char *)phone;

- (int)getTransitionType:(char *)phone;
- (int)getTransitionDurationFixed:(char *)phone;
- (float)getTransitionDurationProp:(char *)phone;


- saveToFile:(FILE *)fp1;
- ReadFromFile:(FILE *)fp1;
@end
