
/* Generated by Interface Builder */

#import <objc/Object.h>
#import <sys/param.h>
#import <stdio.h>

@interface FileManager:Object
{
    id	template;
    id	categories; 
    id	phones;
    id	rule;
    id  generate;
    id  synthesize;

    id  savePanel;
    id  openPanel;

    char currentFile[256];
    char currentDirectory[MAXPATHLEN];
    char currentPath[MAXPATHLEN];
    char dbPath[MAXPATHLEN];
    char dbDirectory[MAXPATHLEN];
}

- appDidInit:sender;
- save:sender;
- saveAs:sender;
- saveLogAs:log;
- open:sender;
- (int)openDBFile:(FILE **)fp;
- setTitles;
- (char *)currentPath;
- (char *)dbPath;
@end
