
/* Generated by Interface Builder */

#import "NXImageView.h"
#import <appkit/NXImage.h>

@implementation NXImageView

- initSize:(NXSize *)size Image:anImage
{
    NXRect rect;
    rect.origin.x = rect.origin.y = 0.0;
    rect.size.height = size->height;
    rect.size.width = size->width;

    [super initFrame:&rect];
    viewImage = anImage;

    return self;
}

- drawSelf:(const NXRect *)rects:(int)rectCount
{
    NXPoint point;

    point.x = point.y = 0.0;
    [viewImage composite:NX_SOVER toPoint:&point];
    return self;
}

@end
