
/* Generated by Interface Builder */

#import <appkit/View.h>
#import "Rule.h"

@interface SpecialEventView:View
{
    id  cache;
    id  backgroundcache;

    float full_range;

    float extent_width;
    float extent_height;
    float vertical_div_height;
    float unity_extent_width;
    float unity_extent_height;

    float graph_origin_x;
    float graph_origin_y;
    float zero_x;
    float zero_y;
    float one_x;

}

+ alloc;
- initFrame:(const NXRect *)viewFrame;
- makeBitmapCache;
- makeBackgroundCache;
- createbackground:(float)range;
- blankDisplay;
- zoomOutDisplay:(specifierStructPtr)specifier:(specialEventStructPtr)specialEvent;
- zoomInDisplay:(specifierStructPtr)specifier:(specialEventStructPtr)specialEvent:
                (se_intervalPtr)se_Interval:(int)regression;

@end
