
/* Generated by Interface Builder */

#import <appkit/View.h>
#import "Rule.h"

@interface TransitionView:View
{
    id  cache;
    id  backgroundcache;

    float extent_width;
    float extent_height;
    float vertical_div_height;
    float unity_extent_width;
    float unity_extent_height;

    float graph_origin_x;
    float graph_origin_y;
    float zero_x;
    float zero_y;
    float one_x;
    float one_y;

    float proportional_space;
    float fixed_space;
    int fixed_total_duration;
    int number_of_p_intervals;
    int number_of_f_intervals;
}

+ alloc;
- initFrame:(const NXRect *)viewFrame;
- makeBitmapCache;
- makeBackgroundCache;
- createbackground;
- displayTransition:(specifierStructPtr)specifier;

@end
