/* Generated by Interface Builder */

#import <appkit/Application.h>

@interface BigMouth:Application
{
    id	mySpeaker;

    id  infoPanel;
    id  preferencesWindow;
    id  scratchpad;
    id  scratchpadWindow;

    int mode;

    char *textBuffer;
    int  textLength;
    NXStream *fileStream;
    char *filename;
}

- appDidInit:sender;
- connectToTTSServer;
- free;
- ttsInstance;

- warnUser;

- (BOOL)appAcceptsAnotherFile:sender;
- (int)app:sender openFile:(const char *)pathname type:(const char *)aType;

- speak:myPasteboard userData:(const char*)userData error:(char**)message;
- speakFile:(const char *)pathname;

- pause:sender;
- continue:sender;
- stopSpeaking:sender;
- repeat:sender;
- setModeToScratchpad;

- showInfo:sender;
- showPreferences:sender;
- showScratchpadWindow:sender;

@end
