#*
#*    Filename:	Makefile 
#*    Created :	Mon Feb 24 00:07:05 1992 
#*    Author  :	Vince DeMarco
#*		<vince@whatnxt.cuc.ab.ca>
#*


MAKELIBDIR = .
CFILES     = conversion.c 
MFILES     = PrDict.m preditorDict.m
HFILES     = PrDict.h preditorDict.h conversion.h
OFILES     = PrDict.o preditorDict.o conversion.o
LIBNAME    = preditorDict.a

include $(MAKELIBDIR)/lib.make

-include Makefile.dependencies
